
#### mumeros listados
GET https://easy2use.com.br/mvno/api/public/linhas/11?user_token={aW4oKkAzOTI0bjEhfDY4NTV8SkQxMjNAMzIxKiM2Mjc}
#### Assinantes listados
GET https://easy2use.com.br/mvno/api/public/assinantes/listar?user_token={aW4oKkAzOTI0bjEhfDY4NTV8SkQxMjNAMzIxKiM2Mjc} -H 
content-type: application/json

#### consumo listados
POST  https://easy2use.com.br/mvno/api/public/consumo-consolidado?user_token={aW4oKkAzOTI0bjEhfDY4NTV8SkQxMjNAMzIxKiM2Mjc} 
content-type: application/json

{"periodo":"2023-01"}

#### consumo listados
GET  http://localhost:3003/data-client/88935001928
content-type: application/json

######## email
POST http://localhost:3003/send-email
content-type: application/json

{
    "name":"Teste2",
    "whatsApp":"3232323232",
    "email":"teste2@teste2.com",
    "street":"rua dos teste2s",
    "num":"001",
    "district":"Bairro dos teste2s",
    "city":"city Teste2",
    "description":"Estamos Fazendo um teste2!!!"
}